export const  CountryCodeList = [
      { countryName: 'Algeria (+213)', countryCode: '213' },
      { countryName: 'Andorra (+376)', countryCode: '376' },
      { countryName: 'Angola (+244)', countryCode: '244' },
      { countryName: 'Anguilla (+1264)', countryCode: '1264' },
      { countryName: 'Antigua &amp; Barbuda (+1268)', countryCode: '1268' },
      { countryName: 'Argentina (+54)', countryCode: '54' },
      { countryName: 'Armenia (+374)', countryCode: '374' },
      { countryName: 'Aruba (+297)', countryCode: '297' },
      { countryName: 'Australia (+61)', countryCode: '61' },
      { countryName: 'Austria (+43)', countryCode: '43' },
      { countryName: 'Azerbaijan (+994)', countryCode: '994' },
      { countryName: 'Bahamas (+1242)', countryCode: '1242' },
      { countryName: 'Bahrain (+973)', countryCode: '973' },
      { countryName: 'Bangladesh (+880)', countryCode: '880' },
      { countryName: 'Barbados (+1246)', countryCode: '1246' },
      { countryName: 'Belarus (+375)', countryCode: '375' },
      { countryName: 'Belgium (+32)', countryCode: '32' },
      { countryName: 'Belize (+501)', countryCode: '501' },
      { countryName: 'Benin (+229)', countryCode: '229' },
      { countryName: 'Bermuda (+1441)', countryCode: '1441' },
      { countryName: 'Bhutan (+975)', countryCode: '975' },
      { countryName: 'Bolivia (+591)', countryCode: '591' },
      { countryName: 'Bosnia Herzegovina (+387)', countryCode: '387' },
      { countryName: 'Botswana (+267)', countryCode: '267' },
      { countryName: 'Brazil (+55)', countryCode: '55' },
      { countryName: 'Brunei (+673)', countryCode: '673' },
      { countryName: 'Bulgaria (+359)', countryCode: '359' },
      { countryName: 'Burkina Faso (+226)', countryCode: '226' },
      { countryName: 'Burundi (+257)', countryCode: '257' },
      { countryName: 'Cambodia (+855)', countryCode: '855' },
      { countryName: 'Cameroon (+237)', countryCode: '237' },
      { countryName: 'Canada (+1)', countryCode: '1' },
      { countryName: 'Cape Verde Islands (+238)', countryCode: '238' },
      { countryName: 'Cayman Islands (+1345)', countryCode: '1345' },
      { countryName: 'Central African Republic (+236)', countryCode: '236' },
      { countryName: 'Chile (+56)', countryCode: '56' },
      { countryName: 'China (+86)', countryCode: '86' },
      { countryName: 'Colombia (+57)', countryCode: '57' },
      { countryName: 'Comoros (+269)', countryCode: '269' },
      { countryName: 'Congo (+242)', countryCode: '242' },
      { countryName: 'Cook Islands (+682)', countryCode: '682' },
      { countryName: 'Costa Rica (+506)', countryCode: '506' },
      { countryName: 'Croatia (+385)', countryCode: '385' },
      { countryName: 'Cuba (+53)', countryCode: '53' },
      { countryName: 'Cyprus North (+90392)', countryCode: '90392' },
      { countryName: 'Cyprus South (+357)', countryCode: '357' },
      { countryName: 'Czech Republic (+42)', countryCode: '42' },
      { countryName: 'Denmark (+45)', countryCode: '45' },
      { countryName: 'Djibouti (+253)', countryCode: '253' },
      { countryName: 'Dominica (+1809)', countryCode: '1809' },
      { countryName: 'Dominican Republic (+1809)', countryCode: '1809' },
      { countryName: 'Ecuador (+593)', countryCode: '593' },
      { countryName: 'Egypt (+20)', countryCode: '20' },
      { countryName: 'El Salvador (+503)', countryCode: '503' },
      { countryName: 'Equatorial Guinea (+240)', countryCode: '240' },
      { countryName: 'Eritrea (+291)', countryCode: '291' },
      { countryName: 'Estonia (+372)', countryCode: '372' },
      { countryName: 'Ethiopia (+251)', countryCode: '251' },
      { countryName: 'Falkland Islands (+500)', countryCode: '500' },
      { countryName: 'Faroe Islands (+298)', countryCode: '298' },
      { countryName: 'Fiji (+679)', countryCode: '679' },
      { countryName: 'Finland (+358)', countryCode: '358' },
      { countryName: 'France (+33)', countryCode: '33' },
      { countryName: 'French Guiana (+594)', countryCode: '594' },
      { countryName: 'French Polynesia (+689)', countryCode: '689' },
      { countryName: 'Gabon (+241)', countryCode: '241' },
      { countryName: 'Gambia (+220)', countryCode: '220' },
      { countryName: 'Georgia (+7880)', countryCode: '7880' },
      { countryName: 'Germany (+49)', countryCode: '49' },
      { countryName: 'Ghana (+233)', countryCode: '233' },
      { countryName: 'Gibraltar (+350)', countryCode: '350' },
      { countryName: 'Greece (+30)', countryCode: '30' },
      { countryName: 'Greenland (+299)', countryCode: '299' },
      { countryName: 'Grenada (+1473)', countryCode: '1473' },
      { countryName: 'Guadeloupe (+590)', countryCode: '590' },
      { countryName: 'Guam (+671)', countryCode: '671' },
      { countryName: 'Guatemala (+502)', countryCode: '502' },
      { countryName: 'Guinea (+224)', countryCode: '224' },
      { countryName: 'Guinea - Bissau (+245)', countryCode: '245' },
      { countryName: 'Guyana (+592)', countryCode: '592' },
      { countryName: 'Haiti (+509)', countryCode: '509' },
      { countryName: 'Honduras (+504)', countryCode: '504' },
      { countryName: 'Hong Kong (+852)', countryCode: '852' },
      { countryName: 'Hungary (+36)', countryCode: '36' },
      { countryName: 'Iceland (+354)', countryCode: '354' },
      { countryName: 'India (+91)', countryCode: '91' },
      { countryName: 'Indonesia (+62)', countryCode: '62' },
      { countryName: 'Iran (+98)', countryCode: '98' },
      { countryName: 'Iraq (+964)', countryCode: '964' },
      { countryName: 'Ireland (+353)', countryCode: '353' },
      { countryName: 'Israel (+972)', countryCode: '972' },
      { countryName: 'Italy (+39)', countryCode: '39' },
      { countryName: 'Jamaica (+1876)', countryCode: '1876' },
      { countryName: 'Japan (+81)', countryCode: '81' },
      { countryName: 'Jordan (+962)', countryCode: '962' },
      { countryName: 'Kazakhstan (+7)', countryCode: '7' },
      { countryName: 'Kenya (+254)', countryCode: '254' },
      { countryName: 'Kiribati (+686)', countryCode: '686' },
      { countryName: 'Korea North (+850)', countryCode: '850' },
      { countryName: 'Korea South (+82)', countryCode: '82' },
      { countryName: 'Kuwait (+965)', countryCode: '965' },
      { countryName: 'Kyrgyzstan (+996)', countryCode: '996' },
      { countryName: 'Laos (+856)', countryCode: '856' },
      { countryName: 'Latvia (+371)', countryCode: '371' },
      { countryName: 'Lebanon (+961)', countryCode: '961' },
      { countryName: 'Lesotho (+266)', countryCode: '266' },
      { countryName: 'Liberia (+231)', countryCode: '231' },
      { countryName: 'Libya (+218)', countryCode: '218' },
      { countryName: 'Liechtenstein (+417)', countryCode: '417' },
      { countryName: 'Lithuania (+370)', countryCode: '370' },
      { countryName: 'Luxembourg (+352)', countryCode: '352' },
      { countryName: 'Macao (+853)', countryCode: '853' },
      { countryName: 'Macedonia (+389)', countryCode: '389' },
      { countryName: 'Madagascar (+261)', countryCode: '261' },
      { countryName: 'Malawi (+265)', countryCode: '265' },
      { countryName: 'Malaysia (+60)', countryCode: '60' },
      { countryName: 'Maldives (+960)', countryCode: '960' },
      { countryName: 'Mali (+223)', countryCode: '223' },
      { countryName: 'Malta (+356)', countryCode: '356' },
      { countryName: 'Marshall Islands (+692)', countryCode: '692' },
      { countryName: 'Martinique (+596)', countryCode: '596' },
      { countryName: 'Mauritania (+222)', countryCode: '222' },
      { countryName: 'Mayotte (+269)', countryCode: '269' },
      { countryName: 'Mexico (+52)', countryCode: '52' },
      { countryName: 'Micronesia (+691)', countryCode: '691' },
      { countryName: 'Moldova (+373)', countryCode: '373' },
      { countryName: 'Monaco (+377)', countryCode: '377' },
      { countryName: 'Mongolia (+976)', countryCode: '976' },
      { countryName: 'Montserrat (+1664)', countryCode: '1664' },
      { countryName: 'Morocco (+212)', countryCode: '212' },
      { countryName: 'Mozambique (+258)', countryCode: '258' },
      { countryName: 'Myanmar (+95)', countryCode: '95' },
      { countryName: 'Namibia (+264)', countryCode: '264' },
      { countryName: 'Nauru (+674)', countryCode: '674' },
      { countryName: 'Nepal (+977)', countryCode: '977' },
      { countryName: 'Netherlands (+31)', countryCode: '31' },
      { countryName: 'New Caledonia (+687)', countryCode: '687' },
      { countryName: 'New Zealand (+64)', countryCode: '64' },
      { countryName: 'Nicaragua (+505)', countryCode: '505' },
      { countryName: 'Niger (+227)', countryCode: '227' },
      { countryName: 'Nigeria (+234)', countryCode: '234' },
      { countryName: 'Niue (+683)', countryCode: '683' },
      { countryName: 'Norfolk Islands (+672)', countryCode: '672' },
      { countryName: 'Northern Marianas (+670)', countryCode: '670' },
      { countryName: 'Norway (+47)', countryCode: '47' },
      { countryName: 'Oman (+968)', countryCode: '968' },
      { countryName: 'Pakistan +92', countryCode: '92' },
      { countryName: 'Palau (+680)', countryCode: '680' },
      { countryName: 'Panama (+507)', countryCode: '507' },
      { countryName: 'Papua New Guinea (+675)', countryCode: '675' },
      { countryName: 'Paraguay (+595)', countryCode: '595' },
      { countryName: 'Peru (+51)', countryCode: '51' },
      { countryName: 'Philippines (+63)', countryCode: '63' },
      { countryName: 'Poland (+48)', countryCode: '48' },
      { countryName: 'Portugal (+351)', countryCode: '351' },
      { countryName: 'Puerto Rico (+1787)', countryCode: '1787' },
      { countryName: 'Qatar (+974)', countryCode: '974' },
      { countryName: 'Reunion (+262)', countryCode: '262' },
      { countryName: 'Romania (+40)', countryCode: '40' },
      { countryName: 'Russia (+7)', countryCode: '7' },
      { countryName: 'Rwanda (+250)', countryCode: '250' },
      { countryName: 'San Marino (+378)', countryCode: '378' },
      { countryName: 'Sao Tome &amp; Principe (+239)', countryCode: '239' },
      { countryName: 'Saudi Arabia (+966)', countryCode: '966' },
      { countryName: 'Senegal (+221)', countryCode: '221' },
      { countryName: 'Serbia (+381)', countryCode: '381' },
      { countryName: 'Seychelles (+248)', countryCode: '248' },
      { countryName: 'Sierra Leone (+232)', countryCode: '232' },
      { countryName: 'Singapore (+65)', countryCode: '65' },
      { countryName: 'Slovak Republic (+421)', countryCode: '421' },
      { countryName: 'Slovenia (+386)', countryCode: '386' },
      { countryName: 'Solomon Islands (+677)', countryCode: '677' },
      { countryName: 'Somalia (+252)', countryCode: '252' },
      { countryName: 'South Africa (+27)', countryCode: '27' },
      { countryName: 'Spain (+34)', countryCode: '34' },
      { countryName: 'Sri Lanka (+94)', countryCode: '94' },
      { countryName: 'St. Helena (+290)', countryCode: '290' },
      { countryName: 'St. Kitts (+1869)', countryCode: '1869' },
      { countryName: 'St. Lucia (+1758)', countryCode: '1758' },
      { countryName: 'Sudan (+249)', countryCode: '249' },
      { countryName: 'Suriname (+597)', countryCode: '597' },
      { countryName: 'Swaziland (+268)', countryCode: '268' },
      { countryName: 'Sweden (+46)', countryCode: '46' },
      { countryName: 'Switzerland (+41)', countryCode: '41' },
      { countryName: 'Syria (+963)', countryCode: '963' },
      { countryName: 'Taiwan (+886)', countryCode: '886' },
      { countryName: 'Tajikstan (+7)', countryCode: '7' },
      { countryName: 'Thailand (+66)', countryCode: '66' },
      { countryName: 'Togo (+228)', countryCode: '228' },
      { countryName: 'Tonga (+676)', countryCode: '676' },
      { countryName: 'Trinidad &amp; Tobago (+1868)', countryCode: '1868' },
      { countryName: 'Tunisia (+216)', countryCode: '216' },
      { countryName: 'Turkey (+90)', countryCode: '90' },
      { countryName: 'Turkmenistan (+7)', countryCode: '7' },
      { countryName: 'Turkmenistan (+993)', countryCode: '993' },
      { countryName: 'Turks &amp; Caicos Islands (+1649)', countryCode: '1649' },
      { countryName: 'Tuvalu (+688)', countryCode: '688' },
      { countryName: 'Uganda (+256)', countryCode: '256' },
      { countryName: 'UK (+44)', countryCode: '44' },
      { countryName: 'Ukraine (+380)', countryCode: '380' },
      { countryName: 'United Arab Emirates (+971)', countryCode: '971' },
      { countryName: 'Uruguay (+598)', countryCode: '598' },
      { countryName: 'USA (+1)', countryCode: '1' },
      { countryName: 'Uzbekistan (+7)', countryCode: '7' },
      { countryName: 'Vanuatu (+678)', countryCode: '678' },
      { countryName: 'Vatican City (+379)', countryCode: '379' },
      { countryName: 'Venezuela (+58)', countryCode: '58' },
      { countryName: 'Vietnam (+84)', countryCode: '84' },
      { countryName: 'Virgin Islands - British (+1284)', countryCode: '84' },
      { countryName: 'Virgin Islands - US (+1340)', countryCode: '84' },
      { countryName: 'Wallis &amp; Futuna (+681)', countryCode: '681' },
      { countryName: 'Yemen (North)(+969)', countryCode: '969' },
      { countryName: 'Yemen (South)(+967)', countryCode: '967' },
      { countryName: 'Zambia (+260)', countryCode: '260' },
      { countryName: 'Zimbabwe (+263)', countryCode: '263' }
    ]
// export {CountryCodeList, const1, const2};

